from pathlib import Path


def _template() -> str:
    return Path("app/modules/equipment_types/templates/master_data_workspace.html").read_text(encoding="utf-8")


def test_master_data_reference_forms_have_explicit_post_actions():
    template = _template()
    # Reference forms are generated by refPanel() from the tree action.
    assert "'/equipment-types/categories/create'" in template
    assert "'/equipment-types/create'" in template
    assert "/equipment-types/brands/create" in template
    assert 'method="post"' in template


def test_new_model_action_is_navigation_owned_and_does_not_scroll_page():
    template = _template()
    assert "window.scrollTo" not in template
    assert "$('modelName').focus()" in template
    assert 'data-add="model"' in template
    assert 'data-new-ref="model"' in template
    assert 'id="newModelTop"' not in template


def test_navigation_click_handler_prioritizes_inline_actions_and_toggles():
    click_handler = Path("static/js/master-data-nav.js").read_text(encoding="utf-8").split(
        "nav.addEventListener('click'", 1
    )[1]
    for hook in (
        "[data-add],[data-new-ref]",
        "[data-tree-add]",
        "[data-copy]",
        "[data-delete]",
        "[data-edit]",
        ".tree-toggle",
        "[data-expand]",
        "[data-model-row]",
        "[data-model]",
        "[data-ref-item]",
    ):
        assert hook in click_handler
    action = click_handler.index("const action = event.target.closest('[data-add],[data-new-ref]')")
    row = click_handler.index("const row = event.target.closest('[data-model-row]')")
    model = click_handler.index("const model = event.target.closest('[data-model]')")
    ref = click_handler.index("const ref = event.target.closest('[data-ref-item]')")
    assert action < row < model < ref
