from pathlib import Path


def _template() -> str:
    return Path("app/modules/equipment_types/templates/master_data_workspace.html").read_text(encoding="utf-8")


def test_master_data_reference_forms_have_explicit_post_actions():
    template = _template()
    # Reference forms are generated by refPanel() from the tree action.
    assert "'/equipment-types/categories/create'" in template
    assert "'/equipment-types/create'" in template
    assert "'/equipment-types/brands/create'" in template
    assert "'/equipment-types/specs/create'" in template
    assert 'method="post"' in template


def test_new_model_action_is_tree_owned_and_does_not_scroll_page():
    template = _template()
    assert "window.scrollTo" not in template
    assert "$('modelName').focus()" in template
    assert 'data-add="model"' in template
    assert 'data-new-ref="model"' in template
    assert 'id="newModelTop"' not in template


def test_tree_click_handler_prioritizes_inline_actions_and_toggles():
    template = _template()
    handler = template[template.index("$('tree').addEventListener('click'"):]
    assert "[data-tree-add]" in handler
    assert "[data-copy]" in handler
    assert "[data-delete]" in handler
    assert "[data-model-row]" in handler
    assert "[data-model]" in handler
    assert "[data-ref-item]" in handler
    assert "[data-tree-add]" in handler
    assert "[data-model-row]" in handler
    assert "[data-model]" in handler
    assert "[data-ref-item]" in handler
    assert "[data-tree-add]" in handler.index("$('tree').addEventListener('click'") and "[data-model]" in handler
