"""add image_url to equipment_models

Revision ID: 5c68afc7b0d3
Revises: stage9_seed_maintenance_operation_library
Create Date: 2026-09-30 14:21:25.453365
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c68afc7b0d3'
down_revision: Union[str, Sequence[str], None] = 'stage9_seed_maintenance_operation_library'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_operation_merge_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_operation_merge_audit_source_rule_id'))

    op.drop_table('maintenance_operation_merge_audit')
    with op.batch_alter_table('equipment_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('equipment_type_spec_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_type_spec_definitions_spec'))

    with op.batch_alter_table('maintenance_operation_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_operation_groups_id'), ['id'], unique=False)

    with op.batch_alter_table('maintenance_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_operations_id'), ['id'], unique=False)

    with op.batch_alter_table('maintenance_plan_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plan_operations_id'), ['id'], unique=False)

    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plans_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_id'))

    with op.batch_alter_table('maintenance_plan_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_operations_id'))

    with op.batch_alter_table('maintenance_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_operations_id'))

    with op.batch_alter_table('maintenance_operation_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_operation_groups_id'))

    with op.batch_alter_table('equipment_type_spec_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_type_spec_definitions_spec'), ['spec_definition_id'], unique=False)

    with op.batch_alter_table('equipment_models', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('maintenance_operation_merge_audit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_rule_id', sa.INTEGER(), nullable=False),
    sa.Column('signature_key', sa.VARCHAR(length=500), nullable=False),
    sa.Column('operation_id', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['source_rule_id'], ['maintenance_rules.id'], name=op.f('fk_maintenance_operation_merge_audit_source_rule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_operation_merge_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_operation_merge_audit_source_rule_id'), ['source_rule_id'], unique=False)

    # ### end Alembic commands ###
