"""expand technical spec groups

Revision ID: d5541feaed19
Revises: 0031_model_custom_specs
Create Date: 2026-09-22 22:36:07.580032
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5541feaed19'
down_revision: Union[str, Sequence[str], None] = '0031_model_custom_specs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_model_spec_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('group_sort_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_model_spec_definitions', schema=None) as batch_op:
        batch_op.drop_column('group_sort_order')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
