"""add technical spec applicability

Revision ID: da62b4ffe6fd
Revises: d5541feaed19
Create Date: 2026-09-22 22:38:09.699734
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da62b4ffe6fd'
down_revision: Union[str, Sequence[str], None] = 'd5541feaed19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_model_spec_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_model_spec_definitions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_model_spec_definitions_equipment_type_id'), ['equipment_type_id'], unique=False)
        batch_op.create_foreign_key('fk_spec_def_equipment_type', 'equipment_types', ['equipment_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_spec_def_category', 'equipment_categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_model_spec_definitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spec_def_category', type_='foreignkey')
        batch_op.drop_constraint('fk_spec_def_equipment_type', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_equipment_model_spec_definitions_equipment_type_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_model_spec_definitions_category_id'))
        batch_op.drop_column('category_id')
        batch_op.drop_column('equipment_type_id')

    # ### end Alembic commands ###
